name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Install poetry ${{ matrix.poetry-version }}
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry==1.1.5
    - name: Install dependencies for project
      run: poetry install --quiet
    - name: Copy the contrib folder
      run: cp contrib/env-sample .env
    - name: Lint with flake8
      run: poetry run flake8 -q
    - name: Run pytest-Django
      run: poetry run pytest --cov=djangoproject
    - name: after success notify codecov report
      if: ${{ success() }}
      run: poetry run codecov



